# docker-compose.yml
version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - NODE_TYPE=server
      - NODE_ID=server
      - HOSTNAME=poker-server.local
    networks:
      poker_network:
        aliases:
          - poker-server.local
    volumes:
      - ./src/server:/app/MentalPoker/src/server

  player1:
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: player1
    environment:
      - NODE_TYPE=client
      - NODE_ID=player1.local
      - HOSTNAME=player1.local
      - SERVER_HOST=poker-server.local
    networks:
      poker_network:
        aliases:
          - player1.local
    depends_on:
      - server

  player2:
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: player2
    environment:
      - NODE_TYPE=client
      - NODE_ID=player2
      - SERVER_HOST=poker-server.local
      - HOSTNAME=player2.local

    networks:
      poker_network:
        aliases:
          - player2.local
    depends_on:
      - server

  player3:
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: player3
    environment:
      - NODE_TYPE=client
      - NODE_ID=player3
      - SERVER_HOST=poker-server.local
      - HOSTNAME=player3.local
    networks:
      poker_network:
        aliases:
          - player3.local
    depends_on:
      - server

  player4:
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: player4
    environment:
      - NODE_TYPE=client
      - NODE_ID=player4
      - SERVER_HOST=poker-server.local
      - HOSTNAME=player4.local
    networks:
      poker_network:
        aliases:
          - player4.local
    depends_on:
      - server

  # player5:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player5
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player5
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player5.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player5.local
  #   depends_on:
  #     - server

  # player6:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player6
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player6
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player6.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player6.local
  #   depends_on:
  #     - server

  # player7:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player7
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player7
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player7.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player7.local
  #   depends_on:
  #     - server

  # player8:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player8
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player8
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player8.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player8.local
  #   depends_on:
  #     - server

  # player9:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player9
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player9
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player9.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player9.local
  #   depends_on:
  #     - server

  # player10:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   hostname: player10
  #   environment:
  #     - NODE_TYPE=client
  #     - NODE_ID=player10
  #     - SERVER_HOST=poker-server.local
  #     - HOSTNAME=player10.local
  #   networks:
  #     poker_network:
  #       aliases:
  #         - player10.local
  #   depends_on:
  #     - server
    

      

networks:
  poker_network:
    driver: bridge